# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5058e58b8cc14470f80df6a0b1e1c3308d9031b1e73b384077bec7eaa78b83eb50486b4e3742ca68034cdbccc2f55ad612b76633c3454c2e1ca4992989e257dd

test:
  secret_key_base: f482c8737842f65c6aebbf0df30eee1d41e0884f0107eb6986988a405695e17ae5c35f0e531436bc17f45aef23e79344d628b537a0b62c6b7530e8e035f9d0c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
